version: "3.1"
services:
  node:
    build: ./
    restart: always
    volumes:
        - ./src:/code/src
    ports:
      - "8081:8081"
    environment:
      - VIRTUAL_HOST=escaperoom.lenders.dev
      - LETSENCRYPT_HOST=escaperoom.lenders.dev
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    external:
      name: reverse-proxy_external
