version: "3.1"
services:
  node:
    build: ./
    volumes:
        - ./src:/code/src
    ports:
      - "8081:8081"
    environment:
      - VIRTUAL_HOST=escaperoom.seppe.dev
      - LETSENCRYPT_HOST=escaperoom.seppe.dev
    network_mode: bridge
